#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 11 09:33:44 2021

@author: siddharthgehlot
"""

#compare how many tuples are there such that 

a=[1,2]
b=[-1,2]
c=[1,-2]
d = [-1,-2]
sum1=0
map={}
for i in range(len(a)):
    for j in range(len(b)):
        s = a[i]+b[j]
        map[s]=0
for k in range(len(c)):
  for l in range(len(d)):
       s1 = -(c[k]+d[l])
       
       if s1 in map:
          map[s1]+=1
      

for key,val in map.items():
     
     sum1+=val
print(sum1)        