#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 19 08:32:47 2021

@author: siddharthgehlot
"""

#Given an array of integer, return the indices of 2 numbers that add up to give a target value 
# [1,3,7,9,2]  11
arr = [1,3,7,9,2]
def twosum(arr,n):
    if len(arr)==0:
        return []
    else:
        
      for i,num in enumerate(arr):
        a = n-num
        for ind,b in enumerate(arr):
             
             if b==a:
            
                return i,ind 
             
             
            
print(twosum([1,3,7,9,2],11))  
print(twosum([],11))
print(twosum([1,3,7,9,2],25))
     