#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  6 12:29:52 2021

@author: siddharthgehlot
"""
array = [1,8,6,2,9,4]
def container(array):
     pt1 = 0
     pt2 = len(array)-1
     maxarea = 0


     while pt2>pt1:
       area = min(array[pt1],array[pt2])*(pt2-pt1)
       if area > maxarea:
             maxarea = area
       if array[pt1]>array[pt2]:
             pt2-=1
       else:
             pt1+=1

     return maxarea 

    
print(container(array))
