#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 11 08:27:55 2021

@author: siddharthgehlot
"""

#given an array find if it contains integers

array=[1,2,3,4]


def duplicates(array):
    map={}
    for i in range(len(array)):
        if array[i] in map:
            map[array[i]]+=1
            if map[array[i]]>1:
                return True
            
        else:
            map[array[i]]=1
    print(map)        
    return False

print(duplicates(array))        