#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 11 08:39:39 2021

@author: siddharthgehlot
"""

#check for anagram and return words in group 
array = ['tea','eat','tan','ate','nat','bat']
def anagram(word1,word2):
    a1 = list(word1)
    a2 = list(word2)
    pt1 = 0
    while len(a1)!=0:
       if len(a1)>0: 
         
        val = a1.pop(pt1)
        
        if val in a2:
            a2.remove(val)
            
          
    if len(a1)==0 and len(a2)==0:
           return True
    return False


#print(anagram('tea','tan'))  



def anagramGroup(array):
      a=[]
      res =[]
      for i in range(len(array)): 
          if array[i] is None:
              continue
          a.append(array[i]) 
          for j in range(i+1,len(array)): 
              
              if array[j] is not None:   
                 if anagram(array[i],array[j]):
                     a.append(array[j])
                     array[j]=None
                    
          res.append(a) 
          a=[] 
      return res
      
         
          
          
   
print(anagramGroup(array))  
   