#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 10 10:32:17 2021

@author: siddharthgehlot
"""

#KNIGHT PROBABILTY IN CHESSBOARD
chess_size = 6
chessboard = [[0 for _ in range(chess_size)] for _ in range(chess_size)]
row = 0 
col = 0
direction = [[2,1],[2,-1],[1,2],[1,-2],[-2,1],[-2,-1],[-1,2],[-1,-2]]
n=6             
             
def probability(chess_size,row,col,k):
    
    if row<0 or col<0 or row>=chess_size or col>=chess_size:
            return 0
    
    if k==0:
       return 1
    
    prob=0
    for d in direction:
        nextrow = row+d[0]
        nextcol = col+d[1]
        print(k)
        prob+=probability(chess_size,nextrow,nextcol,k-1)/8
        
        
        
    return prob     
        
print(probability(chess_size,2,2,6))


    