#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 19 18:59:19 2021

@author: siddharthgehlot
"""

#linkedlist reversal 
class Node:
    def __init__(self,data):
        self.data = data
        self.next = None

class LinkedList:
    def __init__(self):
        self.head = None
    
    def insertStart(self,data):
        insertNode = Node(data)
        if self.head is None:
            self.head = insertNode 
        else:
           value = self.head
           insertNode.next = value
           self.head = insertNode
    def traverse(self):
       printval = self.head
       while printval is not None:
           print(printval.data)
           printval = printval.next

    
            
    def  changeorder(self,list1,m,n):
        value = list1.head
        i=1
        while value is not None and i<m:
           act_val_start = value
           
           value = value.next
           i+=1
        start = value
        #print(start.data)
        #print(act_val_start.data)
        while value is not None and i<n:
            act_val_end = value
            
            value = value.next 
            i+=1
            
        end = value 
        act_val_end = end.next
        #print(end.data)
        #print(act_val_end.data)
        
        act_val_start.next = None 
        end.next = None 
        
        val = start
        node = None
        while val is not None:
            
             nextval = val.next
             val.next = node
             node = val
             val = nextval
             
        if val is None:
             self.head=node        
       
        act_val_start.next = self.head
        self.head = act_val_start
        
        val1 = self.head
        while val1.next is not None:
            
            val1 = val1.next 
            
        val1.next = act_val_end
        act_val_end.next = None 
        
        
        
        
       
       
             
            
                 
             
             
             
        
       
        
       
if __name__=='__main__':
    ll = LinkedList()
    ll.insertStart(5)
    ll.insertStart(4)
    ll.insertStart(3)
    ll.insertStart(2)
    ll.insertStart(1)
    #ll.reverse(ll.head)
    ll.changeorder(ll,2,4)
    ll.traverse()
    