#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 17 11:44:47 2021

@author: siddharthgehlot
"""

#merge two sorted linked list and retain the sorting in original linked list
#1>2>5
#4>8>10
#result: 1>2>4>5>8>10

class Node:
    def __init__(self,data):
        self.data = data
        self.next = None
        
           

class LinkedList:
        def __init__(self):
            self.head = None
        
        #insert data at start
        def insertEnd(self,data):
            insertNode = Node(data)
            if self.head is None:
                self.head = insertNode
            else:
                value = self.head 
                while value.next is not None:
                     value = value.next 
                value.next = insertNode 
                
        def traverse(self):
            printval = self.head 
            while printval is not None:
                print(printval.data)
                printval = printval.next          
            
def mergesortedList(list1,list2):
        #list have next attribute
        list3 = LinkedList()
        val1 = list1.head  
        val2 = list2.head
        while val1 is not None and val2 is not None:

            value = list3.head
            if val1.data>=val2.data:
                 value = val2
                 print(value.data)
                 val2 = val2.next
                 if val2 is None:
                     while val1:
                        value.next = val1 
                        print(value.next.data)
                        val1 = val1.next
                     

            else:
                value = val1
                print(value.data)
                val1 = val1.next 
                if val1 is None:
                
                    while val2:
                        value.next = val2 
                        print(value.next.data)
                        val2 = val2.next
                        
                        
            value = value.next
            
            
            
       
            
            
            
            
if __name__=="__main__":
    list1 = LinkedList()
    list1.insertEnd(2)
    list1.insertEnd(4)
    list1.insertEnd(6)
    list1.insertEnd(9)
    list1.insertEnd(10)
    list1.insertEnd(11)
    #list1.traverse() 
    
    
    list2 = LinkedList()
    list2.insertEnd(1)
    list2.insertEnd(3)
    list2.insertEnd(4)
    list2.insertEnd(5)
    #list2.traverse() 
    
   
    #print(list3.head)

    
    mergesortedList(list1,list2)
    
    
    
    
    
            
                
                