#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 17 13:25:29 2021

@author: siddharthgehlot
"""

#linked list reversed

class Node:
    def __init__(self,data):
        self.data = data
        self.next = None
        
           

class LinkedList:
        def __init__(self):
            self.head = None
        
        #insert data at start
        def insertEnd(self,data):
            insertNode = Node(data)
            if self.head is None:
                self.head = insertNode
            else:
                value = self.head 
                while value.next is not None:
                     value = value.next 
                value.next = insertNode 
                
        def traverse(self):
            printval = self.head 
            while printval is not None:
                print(printval.data)
                printval = printval.next  
                
def reverseLinkedList(list1):
    value = list1.head
    node = None
    while value is not None:
           nextval = value.next
           value.next = node
           node = value
           value = nextval
    return node
        
        
           
                 
           
if __name__=='__main__':
     ls = LinkedList()
     ls.insertEnd(1)
     ls.insertEnd(2)
     ls.insertEnd(3)
     ls.insertEnd(4)
     ls.insertEnd(5)
     #ls.traverse() 
     
     res = reverseLinkedList(ls)
     
     while res is not None:
         print(res.data)
         res = res.next
     
     
     

                 
           