#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 17 18:39:19 2021

@author: siddharthgehlot
"""

#linked list odd even linkedlist
#1>2>3>4>5
#1>3>5>2>4


class Node:
    def __init__(self,data):
        self.data = data
        self.next = None
        
           

class LinkedList:
        def __init__(self):
            self.head = None
        
        #insert data at start
        def insertEnd(self,data):
            insertNode = Node(data)
            if self.head is None:
                self.head = insertNode
            else:
                value = self.head 
                while value.next is not None:
                     value = value.next 
                value.next = insertNode 
                
        def traverse(self):
            printval = self.head 
            while printval is not None:
                print(printval.data)
                printval = printval.next 
                

def oddevenll(list1):
    value = list1.head
    
    oddlist = LinkedList()
    evenlist = LinkedList()
   
    while value is not None:
        
        if value.data%2!=0:
           
           oddlist.insertEnd(value.data)
           
        else:
           
           evenlist.insertEnd(value.data)
           
        value = value.next   
           
    oddlist.traverse()
    evenlist.traverse()    

        
        
       
        
    
   
        
    
        
              
if __name__=='__main__':
     ls = LinkedList()
     ls.insertEnd(5)
     ls.insertEnd(7)
     ls.insertEnd(4)
     ls.insertEnd(9)
     ls.insertEnd(8)


     oddevenll(ls)   
                