#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  6 17:05:28 2021

@author: siddharthgehlot
"""
string = 'abccaded'
def longestSubstring(string):
          map={}
          maxlen=0
          a=[]
          s = set(string)
          for i in s:
              map[i]=0


          for ind,j in enumerate(string):
                
                map[j]+=1
                if map[j]<=1:
                    a.append(j)
                    
                if map[j]>1:
                    l=len(a)
                    
                    a =[j]
                    if l>maxlen :
                          maxlen =l
                    for k in s:
                            map[k]=0
                            
          return maxlen
print(longestSubstring(string))




def longestsub(string):
    a=[]
    maxlen=0
    for i in string:
        if i not in a:
            a.append(i)
        else:
            l = len(a)
            if l>maxlen:
                maxlen=l
            a=[]
            a.append(i)
    return maxlen 


print(longestsub(string))        
            
        