#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep  4 10:01:19 2021

@author: siddharthgehlot
"""

#substring with non repeating character in string 

s = 'abcdabcbb'

def substring(string):
    s = 0
    e = 0
    l = set(list(string))
    maxlen =0
    map ={}
    st=''
    for i,val in enumerate(l):    
         map[val]=0
        
         
    while s<len(string):
      
       while e<len(string[s:]) and map[string[e]]<1:  
          
        map[string[e]]+=1
        st+=string[e]
        
        
        e+=1
         
       if maxlen<len(st):
        maxlen = len(st)
        
       s=e+1 
       e=e+1
        
    return maxlen
print(substring(s))    
        
        
        
        
        