#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 31 14:43:29 2021

@author: siddharthgehlot
"""

#longest string 

def substring(string):
    array =list(string)
    lpt =0
    rpt =0
    maxlen =0
    map={}
    for i in array:
       map[i]=0
    
    for n,i in enumerate(array):
        rpt=n
        if rpt-lpt>maxlen:
            maxlen = rpt-lpt
        if map[i]==0:
            map[i]+=1
            maxlen+=1
            rpt+=1
        else:
            lpt=rpt
            l =maxlen
            maxlen=0
            for key,value in map.items():
                map[key]=0
        
        
    return l
print(substring('abccabeb'))        
            
            