#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 28 12:52:00 2021

@author: siddharthgehlot
"""

#max container using pointer shifting method

ls1 = [1,8,6,2,9,4]
def maxcontainer(ls):
    a = 0
    b = len(ls)-1
    maxarea=0
    while a<len(ls) and b>=0:
        print(a,b)
        area = min(ls[a],ls[b])*(b-a)
        
        if area > maxarea:
            maxarea = area
            
        if ls[a]>ls[b]:
            b-=1
        else:
            a+=1
    return maxarea        
print(maxcontainer(ls1))    

