#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 28 11:03:55 2021

@author: siddharthgehlot
"""

#find out the container with maximum water capacity


#if the lines are have any area?
#can there be multiple contaienr with max area


#plan 
#[1,8,6,2,9,4]
#area = max(indexdiff)*min(valuediff)
#2 for loops and finding the area for each possible container
#indexdiff for each pair


   

def maxarea(ls,index,maxa):
    
     print(index,maxa)
     for index2 in range(index,len(ls)):
    
      if index ==len(ls)-1:
          return maxa
         
      if ls[index]<ls[index2] : 
         area =min(ls[index],ls[index2])*(index2-index)

         if area>maxa:
            maxa = area
            
            
         break   
            
           
            
     return maxarea(ls,index2,maxa)
     
ls = [1,8,6,2,9,4] 
print(maxarea(ls,0,0))    
           
            
    

