#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep  4 09:00:03 2021

@author: siddharthgehlot
"""

#boat to save people
import math
array = [1,2]
limit =3 
def boats(array,limit):
    n=0
    while len(array)>0:
      actval = array.pop()
      if actval>=limit:
           n=math.ceil(actval/limit)
           
      else:
        while actval<limit:
           actval+=array.pop()
           
        n+=math.ceil(actval/limit)
        
    return n

#print(boats(array,limit))    




#using summation

def sumboats(array,limit):
    s = sum(array)
    return math.ceil(s/limit)
print(sumboats(array,limit))