#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 11 08:07:53 2021

@author: siddharthgehlot
"""

#valid mountain array

array = [3,5,5,4,3,5,1]

#atleast 3 size of the array
#there should be a value such that it is larger than preceeding and smaller than trailing

def mountain(array):
     for i in range(1,len(array)-1):
         if array[i-1]<array[i] and array[i]>array[i+1]:
             return True
         
     return False
         
print(mountain(array))            