#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 10 15:53:53 2021

@author: siddharthgehlot
"""

#boat required to carry each person

person = [3,2,3,2,1,2,2]
limit = 3

def noBoats(person,limit):
    s=0
    i=0
    n=0
   
    while i<len(person):
        s+=person[i]
        
        
    
        if s>=limit:
            num = s%limit
            print(s,num)
            if num==0:
                n+=num+1
            else:    
                n+=num
            
            s=0
        if s<limit and i==len(person)-1:
           
           num = (s//limit)+1
           print(s,num) 
           n+=num
            
        
            
        
        i+=1
    
      
      
    return n


print(noBoats(person,limit))

   
      
     