#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  6 18:09:03 2021

@author: siddharthgehlot
"""

#palindrome
string = 'abbacc'
def palindrome(string):
    count=0
    pt1=0
    pt2 = len(string)-1
    array=list(string)
    while pt1<=pt2:
      if array[pt1]==array[pt2]:
        pt1+=1
        pt2-=1
        count+=2
      else:
          count=0
          pt2-=1
          if array[pt1]==array[pt2]:
              pass
          else:
              pt2+=1
              pt1-=1
          
          
          
    return count  

print(palindrome(string))    




def almostpalindrome(string):
    count=0
    pt1=0
    pt2=len(string)-1
    array=list(string)
    while pt1<=pt2:
      if array[pt1]==array[pt2]:
        pt1+=1
        pt2-=1
        count+=2
      else:
          count=0
          pt2-=1
          if array[pt1]==array[pt2]:
              pass
          else:
              pt2+=1
              pt1-=1
              
    if len(string)-count==1:
        return True
    return False
        
     
print(almostpalindrome(string))  





def palindromeRecursion(string,pt1,pt2,length):
    
    if pt1>=pt2:
        return length 
    if string[pt1]==string[pt2]:
        
          length+=2
          return palindromeRecursion(string,pt1+1,pt2-1,length)
    
    elif string[pt1]!=string[pt2] :
          return max(palindromeRecursion(string,pt1,pt2-1,0),palindromeRecursion(string,pt1+1,pt2,0))
      

    return length          
        
print(palindromeRecursion(string,0,len(string)-1,0))       