#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 12 09:50:14 2021

@author: siddharthgehlot
"""

#reverse linked list 

class Node:
    def __init__(self,data):
        self.data = data
        self.next = None
class LinkedList:
    def __init__(self):
        self.head = None
    def insertStart(self,data):
        insertData = Node(data)
        if self.head is None:
            self.head = Node(data)
        else:
            insertData.next = self.head
            self.head = insertData
            
    def insertEnd(self,data):
         if self.head is None:
             self.head = Node(data)
         else:
             val = self.head 
             while val.next is not None:
                 val = val.next 
                 
             val.next = Node(data)    
          
    def traverse(self):
         printval = self.head 
         while printval is not None:
             print(printval.data)
             printval = printval.next 
             
    def reverse(self):
         val = self.head 
         node = None 
         
         while val is not None:
             nextNode = val.next 
             val.next = node 
             node = val 
             val = nextNode
             
         self.head = node   
             
if __name__=='__main__':
    ll1 = LinkedList()
    ll1.insertEnd(4)
    ll1.insertEnd(2)
    ll1.insertEnd(1)
    ll1.insertEnd(3)
    ll1.insertEnd(8)
    ll1.insertEnd(10)
    ll1.traverse()  
    ll1.reverse()
    print("    ")
    ll1.traverse()           