#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 20 14:56:34 2021

@author: siddharthgehlot
"""

#remove the minimum number of parenthesis to get a valid string

string = 'a(b(cd)e))'
#valid woulb be ab(cd)e

def validate(s):
    cnt = 0
    cnt1=0
    list1 = list(s)
    print(list1)
    j=0
    l=len(list1)-1
    st =''
    for i in list1 :
        if i=='(':
           cnt+=1
    for i in list1:
        if i==')':
          cnt1+=1
    #print(cnt,cnt1)    
    if cnt==cnt1:
        return 'valid string'
    else:
        if cnt>cnt1:
            while cnt>cnt1:
    
                   if list1[j]=='(':
                     #print(list1[j]) 
                     list1.pop(j)
                     j-=1
                     print(list1)
                     
                     
                     cnt-=1
                   j+=1  
        else:
               while cnt1>cnt:
                  
                      if list1[j]==')':
                         list1.pop(j)
                         j-=1
                         print(list1)
                         cnt1-=1
                      j+=1   
                   
    for k in list1:
        st +=k 
        
    return st   
                   
print(validate(string))                   
                                      
              