#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  1 10:06:14 2021

@author: siddharthgehlot
"""
array=[1,3,3,5,5,5,6,6]
def binarysearch(array,start,end,target):
   mid = (start+end)//2
   while start<=end: 
    if array[mid]==target:
        return mid
    elif array[mid]<target:
        start+=1
    else:
        end-=1
    
   return -1


def search(array,target):
    if len(array)<=0:
        return [-1,-1]
    
    firstpos = binarysearch(array,0,len(array)-1,5)
    
    
    startpos = firstpos
    endpos = firstpos 
    
    while startpos!=-1:
        temp1 = startpos
        startpos = binarysearch(array,0,startpos-1,5)
    startpos= temp1    
    while  endpos!=-1:
        temp2=endpos
        endpos = binarysearch(array,endpos+1,len(array)-1,5)
    endpos = temp2
    
    return [startpos,endpos]


print(search(array,5))

    