#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 19 18:48:09 2021

@author: siddharthgehlot
"""

#find the longest substring withotu duplocate character
string = 'abcdcbdd'

def substring(string):
    list1 = list(string)
    list2 =[]
    i=0
    lenstr = 0
    while i<len(list1):
        a= list1.pop(0)
    
        if a not in list2:
            list2.append(a)
        else:
            if lenstr<len(list2):
                lenstr = len(list2)
        
            i =i+1
            
    return lenstr  


print(substring(string))     
            
            
        
        
