#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  6 12:45:48 2021

@author: siddharthgehlot
"""

array=[0,1,0,2,1,0,3,1,0,1,2]
def trappedrainwater(array):
         s=0
         
         dp1=[0]*len(array)
         dp2 = [0]*len(array)
         dp1[0]=0
         dp2[len(array)-1]=array[len(array)-1]
         
         for i in range(1,len(array)):
                 dp1[i] = max(dp1[i-1],array[i])
                 
         for j in range(len(array)-2,-1,-1):
                 dp2[j]=max(dp2[j+1],array[j])
         for i in range(len(array)):
             s+=min(dp1[i],dp2[i])-array[i]
         print(dp1,dp2)
         
         return s 
     
print(trappedrainwater(array))        
