#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  6 11:45:32 2021

@author: siddharthgehlot
"""
Input =[1,3,7,9,2]
Target = 11
diff =[]

#
def twoSumArray(input,target):
       if max(input)>target:
          return False
       for i in range(len(input)):
        if input[i] not in diff:
           diff.append(target-input[i])
       else:
            return input[i],target-input[i]
       return False


print(twoSumArray(Input,Target))