#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  6 11:29:56 2021

@author: siddharthgehlot
"""

Input =[1,3,7,9,2]
Target = 11


#Brute force 
def twoSum(input,target):
    for i in range(len(input)):
      for j in range(i,len(input)):
        
        
        if input[i]+input[j]==target:
            return input[i],input[j]
    
    return False

print(twoSum(Input,Target))
