#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  6 14:55:14 2021

@author: siddharthgehlot
"""
string ='abcd###ef#'
def typedoutpointer(string):
      array=list(string)
      pt1=len(string)-1
      a=[]
      st=''
      while pt1>=0:
          
          if array[pt1]!='#':
              a.append(array[pt1])
              pt1-=1
          else: 
             print(array[pt1]) 
             if array[pt1-1]!='#': 
                 pt1-=1
                 
             else:
                 while array[pt1]=='#':
                       pt1-=1
                 pt1-=2
          pt1-=1       
          
          
          
         
          
      return a  
          
                
            
print(typedoutpointer(string)) 



         
