#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 31 12:30:29 2021

@author: siddharthgehlot
"""
st='abc##d#'
st2 = 'ad#'

def typedstr(st):
    array = list(st)
    a=[]
    st=''
    pointer1 = len(array)-1
    while pointer1>=0:
     if array[pointer1]!='#':
        a.append(array[pointer1])
        pointer1-=1
     else:
        if array[pointer1-1]!='#':
            pointer1-=2
        else:    
           while array[pointer1]=='#':
              pointer1-=1
           pointer1-=2
        print(pointer1)
        
    for i in a:
            st+=i
        
    return st



def compare(st1,st2):
    
    if typedstr(st1)==typedstr(st2):
          
          
          return True
    else:
        
        return False
    
print(compare(st,st2)) 

print(typedstr(st2)) 
        